package com.stop.notification_service.entity;

public enum NotificationType {
    MATCH_STARTED,
    MATCH_UPDATED,
    MATCH_CANCELLED,
    MATCH_COMPLETED,
    INVITATION_RECEIVED,
    PARTICIPANT_JOINED,
    PARTICIPANT_LEFT,
    PARTICIPANT_REMOVED,
    PARTICIPATION_REQUEST_RECEIVED,
    PARTICIPATION_REQUEST_APPROVED,
    PARTICIPATION_REQUEST_REJECTED,
    CHAT_MESSAGE_RECEIVED,
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED
}
