communication:
  cors:
    allowed-origin-patterns:
      - "${ALLOWED_ORIGIN}"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  file:
    name: ""
  level:
    root: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
