package com.stop.api_gateway.error;

public enum GatewayErrorCode {

    TOKEN_MISSING,
    TOKEN_INVALID,
    TOKEN_EXPIRED,
    TOKEN_MALFORMED,
    SIGNATURE_INVALID,

    SERVICE_NOT_FOUND,
    SERVICE_UNAVAILABLE,
    ROUTE_NOT_DEFINED,

    RATE_LIMIT_EXCEEDED,
    TOO_MANY_REQUESTS,

    DOWNSTREAM_TIMEOUT,
    DOWNSTREAM_UNAVAILABLE,
    CIRCUIT_OPEN,

    FORBIDDEN,
    INTERNAL_ERROR
}
